---
- name: Set root Passwordless SSH
  hosts: EVA
  become: yes
  tasks:
    - name: Copy SSH key to authorized_keys
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
